runtime: python39
entrypoint: uvicorn main:app --host 0.0.0.0 --port ${PORT}
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

env_variables:
  DATABASE_URL: 'mongodb+srv://germys:LWBVI45dp8jAIywv@douvery.0oma0vw.mongodb.net/Production'
